### ISSUE TITLE
Question on usage

### ISSUE THREAD

**Issue by VaasKahnGrim** [danielga/scanning#2]
I've noticed this repository being used in other projects both by you and others aswell. I'm wondering how to go about getting a signature for use in a project. For example "\x2A\x2A\x2A\x2A\xE8\x2A\x2A\x2A\x2A\xD8\x6D\x24\x83\x4D\xEC\x10" used in gmsv_serversecure. I'm hoping to be able to revive a few dead projects I've found that no longer work because of old signatures that don't work anymore

**Comment by michak89** [comment]
I'm wondering too, Btw, after last gmod update luapack signature is outdated again.

**Comment by danielga** [comment]
I can't help you there. This is a long and arduous learning path. You need knowledge in assembly (specifically x86) to understand what the disassembled code you're looking at does so you know it's what you want, you need tools to disassemble binaries (and this is where some issues arise due to how gray this area is) and you need lots of knowledge about the Source engine (to help you navigate, otherwise you'll be looking for needles on haystacks over haystacks). One great helper is looking for known strings from the Source engine on your disassembler.
